TCV/TCVWeb/Areas/Admin/Controllers/HomeAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.Encodings.Web;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using TCVShared.Data;
using TCVWeb.Areas.Admin.Models;
using TCVWeb.Models;

namespace TCVWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Manager,Operator")]
    public class HomeAdminController : Controller
    {
        private readonly UserManager<AppUser> _userManager;
        private readonly UrlEncoder _urlEncoder;
        private readonly AppDBContext _dbContext;
        private readonly ILogger _logger;

        private const string AuthenticatorUriFormat = "otpauth://totp/{0}:{1}?secret={2}&issuer={0}&digits=6";

        public HomeAdminController(
            UserManager<AppUser> userManager,
            UrlEncoder urlEncoder,
            AppDBContext dbContext,
            ILogger<HomeAdminController> logger)
        {
            _userManager = userManager;
            _urlEncoder = urlEncoder;
            _dbContext = dbContext;
            _logger = logger;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Profile()
        {
            var appUser = await _userManager.GetUserAsync(User);
            var model = new TwoFactorAuthenticationViewModel
            {
                HasAuthenticator = await _userManager.GetAuthenticatorKeyAsync(appUser) != null,
                Is2faEnabled = appUser.TwoFactorEnabled,
                RecoveryCodesLeft = await _userManager.CountRecoveryCodesAsync(appUser),
            };

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> EnableAuthenticator()
        {
            var appUser = await _userManager.GetUserAsync(User);
            if (appUser == null)
            {
                throw new ApplicationException($"Unable to load appUser with ID '{_userManager.GetUserId(User)}'.");
            }

            var model = new EnableAuthenticatorViewModel();
            await LoadSharedKeyAndQrCodeUriAsync(appUser, model);

            return View(model);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> EnableAuthenticator(EnableAuthenticatorViewModel model)
        {
            var appUser = await _userManager.GetUserAsync(User);
            if (appUser == null)
            {
                throw new ApplicationException($"Unable to load appUser with ID '{_userManager.GetUserId(User)}'.");
            }

            if (!ModelState.IsValid)
            {
                await LoadSharedKeyAndQrCodeUriAsync(appUser, model);
                return View(model);
            }

            var verificationCode = model.Code.Replace(" ", string.Empty).Replace("-", string.Empty);

            var is2faTokenValid = await _userManager.VerifyTwoFactorTokenAsync(
                appUser, _userManager.Options.Tokens.AuthenticatorTokenProvider, verificationCode);

            if (!is2faTokenValid)
            {
                ModelState.AddModelError("Code", "Verification code is invalid.");
                await LoadSharedKeyAndQrCodeUriAsync(appUser, model);
                return View(model);
            }

            await _userManager.SetTwoFactorEnabledAsync(appUser, true);

            var recoveryCodes = await _userManager.GenerateNewTwoFactorRecoveryCodesAsync(appUser, 10);

            var xModel = new ShowRecoveryCodesViewModel { RecoveryCodes = recoveryCodes.ToArray() };
            return View("ShowRecoveryCodes", xModel);
        }

        [HttpGet]
        public IActionResult ResetAuthenticatorWarning()
        {
            return View(nameof(ResetAuthenticator));
        }

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> ResetAuthenticator()
        {
            var appUser = await _userManager.GetUserAsync(User);
            if (appUser == null)
            {
                throw new ApplicationException($"Unable to load appUser with ID '{_userManager.GetUserId(User)}'.");
            }

            await _userManager.SetTwoFactorEnabledAsync(appUser, false);
            await _userManager.ResetAuthenticatorKeyAsync(appUser);

            return RedirectToAction(nameof(EnableAuthenticator));
        }

        [HttpGet]
        public async Task<IActionResult> GenerateRecoveryCodesWarning()
        {
            var appUser = await _userManager.GetUserAsync(User);
            if (appUser == null)
            {
                throw new ApplicationException($"Unable to load appUser with ID '{_userManager.GetUserId(User)}'.");
            }

            if (!appUser.TwoFactorEnabled)
            {
                throw new ApplicationException($"Cannot generate recovery codes for appUser with ID '{appUser.Id}' because they do not have 2FA enabled.");
            }

            return View(nameof(GenerateRecoveryCodes));
        }

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> GenerateRecoveryCodes()
        {
            var appUser = await _userManager.GetUserAsync(User);
            if (appUser == null)
            {
                throw new ApplicationException($"Unable to load appUser with ID '{_userManager.GetUserId(User)}'.");
            }

            if (!appUser.TwoFactorEnabled)
            {
                throw new ApplicationException($"Cannot generate recovery codes for appUser with ID '{appUser.Id}' as they do not have 2FA enabled.");
            }

            var recoveryCodes = await _userManager.GenerateNewTwoFactorRecoveryCodesAsync(appUser, 10);

            var xModel = new ShowRecoveryCodesViewModel { RecoveryCodes = recoveryCodes.ToArray() };
            return View("ShowRecoveryCodes", xModel);
        }

        #region Helpers

        private string FormatKey(string unformattedKey)
        {
            var result = new StringBuilder();
            int currentPosition = 0;
            while (currentPosition + 4 < unformattedKey.Length)
            {
                result.Append(unformattedKey.Substring(currentPosition, 4)).Append(" ");
                currentPosition += 4;
            }
            if (currentPosition < unformattedKey.Length)
            {
                result.Append(unformattedKey.Substring(currentPosition));
            }

            return result.ToString().ToLowerInvariant();
        }

        private string GenerateQrCodeUri(string email, string unformattedKey)
        {
            string appName = string.Format("TCV.Admin.{0}", Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT"));
            return string.Format(
                AuthenticatorUriFormat,
                _urlEncoder.Encode(appName),
                _urlEncoder.Encode(email),
                unformattedKey);
        }

        private async Task LoadSharedKeyAndQrCodeUriAsync(AppUser appUser, EnableAuthenticatorViewModel model)
        {
            var unformattedKey = await _userManager.GetAuthenticatorKeyAsync(appUser);
            if (string.IsNullOrEmpty(unformattedKey))
            {
                await _userManager.ResetAuthenticatorKeyAsync(appUser);
                unformattedKey = await _userManager.GetAuthenticatorKeyAsync(appUser);
            }

            model.SharedKey = FormatKey(unformattedKey);
            model.AuthenticatorUri = GenerateQrCodeUri(appUser.Email, unformattedKey);
        }

        #endregion
    }
}

TCV/TCVWeb/Areas/Admin/Views/HomeAdmin/EnableAuthenticator.cshtml
@using TCVWeb.Areas.Admin.Models
@model EnableAuthenticatorViewModel
@{
    ViewBag.Icon = "fa-check";
    ViewBag.Title = "Tạo mã Authenticator";
}

<section role="main" class="content-body">
    <header class="page-header">
        <h2><i class="fa @ViewBag.Icon"></i> @ViewBag.Title</h2>
        <div class="right-wrapper pull-right">
            <ol class="breadcrumbs">
                <li>
                    <a href="@Url.Action("Index", "Home")">
                        <i class="fa fa-home"></i>
                    </a>
                </li>
                <li><span>Authenticator</span></li>
            </ol>
            <a class="sidebar-right-toggle" data-open="sidebar-right"><i class="fa fa-chevron-left"></i></a>
        </div>
    </header>
    <div class="row">
        <div class="col-sm-4">
            <a class="btn btn-primary" href="@Url.Action("Index")"><i class="fa fa-undo"></i> Quay lại</a>
        </div>
        <div class="col-sm-8 text-right">
        </div>
    </div>
    <div class="mt-md">
        <p>Các bước thực hiện liên kết với ứng dụng Authenticator:</p>
        <ol class="list">
            <li>
                Tải một trong các ứng dụng Authenticator như sau:
                <p>
                    <b>Google Authenticator</b>
                    <ul>
                        <li><a href="https://play.google.com/store/apps/details?id=com.google.android.apps.authenticator2&amp;hl=en" target="_blank">Phiên bản Android</a></li>
                        <li><a href="https://itunes.apple.com/us/app/google-authenticator/id388497605?mt=8" target="_blank">Phiên bản iOS</a></li>
                    </ul>
                </p>
                <p>
                    <b>Microsoft Authenticator</b>
                    <ul>
                        <li><a href="https://go.microsoft.com/fwlink/?Linkid=825071" target="_blank">Phiên bản Windows Phone</a></li>
                        <li><a href="https://go.microsoft.com/fwlink/?Linkid=825072" target="_blank">Phiên bản Android</a></li>
                        <li><a href="https://go.microsoft.com/fwlink/?Linkid=825073" target="_blank">Phiên bản iOS</a></li>
                    </ul>
                </p>
            </li>
            <li>
                <p>Mở ứng dụng rồi quét QRCode dưới đây hoặc nhập đoạn mã <kbd>@Model.SharedKey</kbd></p>
                <div id="qrCode"></div>
                <div id="qrCodeData" data-url="@Model.AuthenticatorUri"></div>
            </li>
            <li>
                <p>
                    Cuối cùng, nhập mã số nhận được từ ứng dụng Authenticator để hoàn tất liên kết
                </p>
                <div class="row">
                    <div class="col-md-6">
                        <form method="post">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <div class="form-group">
                                <label asp-for="Code"></label>
                                <input asp-for="Code" class="form-control" autocomplete="off" />
                                <span asp-validation-for="Code" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <div class="col-sm-6 text-right">
                                    <button type="submit" class="btn btn-primary btn-block hidden-xs"><i class="fa fa-check"></i> Xác nhận</button>
                                    <button type="submit" class="btn btn-primary btn-block btn-lg visible-xs mt-lg"><i class="fa fa-check"></i> Xác nhận</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </li>
        </ol>
    </div>
</section>
@section Scripts {
    <partial name="_PartialValidation" />
    <script type="text/javascript" src="~/js/qrcode.min.js"></script>
    <script type="text/javascript">
        new QRCode(document.getElementById("qrCode"),
            {
                text: "@Html.Raw(Model.AuthenticatorUri)",
                width: 150,
                height: 150
            });
    </script>
}

TCV/TCVWeb/Areas/Admin/Views/HomeAdmin/GenerateRecoveryCodes.cshtml
@{
    ViewBag.Title = "Sinh mã cứu hộ";
}
<section role="main" class="content-body">
    <header class="page-header">
        <h2><i class="fa @ViewBag.Icon"></i> @ViewBag.Title</h2>
        <div class="right-wrapper pull-right">
            <ol class="breadcrumbs">
                <li>
                    <a href="@Url.Action("Index", "Home")">
                        <i class="fa fa-home"></i>
                    </a>
                </li>
                <li><span>Authenticator</span></li>
            </ol>
            <a class="sidebar-right-toggle" data-open="sidebar-right"><i class="fa fa-chevron-left"></i></a>
        </div>
    </header>
    <div class="row">
        <div class="col-sm-4">
            <a class="btn btn-primary" href="@Url.Action("Index")"><i class="fa fa-undo"></i> Quay lại</a>
        </div>
        <div class="col-sm-8 text-right">
        </div>
    </div>
    <div class="mt-md">
        <div class="alert alert-warning" role="alert">
            <p>
                <span class="glyphicon glyphicon-warning-sign"></span>
                <b>Thao tác này sẽ reset lại mã cứu hộ.</b>
            </p>
            <p>
                Nếu bạn mất thiết bị Authenticator, bạn có thể sử dụng mã cứu hộ để đăng nhập Tài khoản
            </p>
            <p>
                Reset mã cứu hộ không làm thay đổi key của ứng dụng Authenticator. Nếu bạn muốn thay đổi key của ứng dụng Authenticator bạn có thể <a asp-action="ResetAuthenticatorWarning"> Reset mã Authenticator.</a>
            </p>
        </div>
        <div>
            <form asp-action="GenerateRecoveryCodes" method="post" class="form-group">
                <button class="btn btn-danger" type="submit"><i class="fa fa-check"></i> Reset lại mã</button>
            </form>
        </div>
    </div>
</section>

TCV/TCVWeb/Areas/Admin/Views/HomeAdmin/Index.cshtml
@{
    ViewBag.Icon = "fa-dashboard";
    ViewBag.Title = "Dashboard";
}
<section role="main" class="content-body">
    <header class="page-header">
        <h2><i class="fa @ViewBag.Icon"></i> @ViewBag.Title</h2>
        <div class="right-wrapper pull-right">
            <ol class="breadcrumbs">
                <li>
                    <a asp-action="Index" asp-controller="HomeAdmin">
                        <i class="fa fa-home"></i>
                    </a>
                </li>
                <li><span>Dashboard</span></li>
            </ol>
            <a class="sidebar-right-toggle" data-open="sidebar-right"><i class="fa fa-chevron-left"></i></a>
        </div>
    </header>
    <div class="row">
        <div class="col-sm-4">
        </div>
        <div class="col-sm-4">
        </div>
        <div class="col-sm-4">
        </div>
    </div>
</section>

TCV/TCVWeb/Areas/Admin/Views/HomeAdmin/Profile.cshtml
@using TCVWeb.Areas.Admin.Models
@model TwoFactorAuthenticationViewModel
@{
    ViewBag.Title = "Dashboard";
}

<section role="main" class="content-body">
    <header class="page-header">
        <h2><i class="fa @ViewBag.Icon"></i> @ViewBag.Title</h2>
        <div class="right-wrapper pull-right">
            <ol class="breadcrumbs">
                <li>
                    <a href="@Url.Action("Index", "Home")">
                        <i class="fa fa-home"></i>
                    </a>
                </li>
                <li><span>Dashboard</span></li>
            </ol>
            <a class="sidebar-right-toggle" data-open="sidebar-right"><i class="fa fa-chevron-left"></i></a>
        </div>
    </header>
    <div class="mt-md">
        <h4>Bảo mật 2 lớp</h4>
        @if (Model.Is2faEnabled)
        {
            if (Model.RecoveryCodesLeft == 0)
            {
                <div class="alert alert-danger">
                    <b>Bạn không còn mã cứu hộ nào</b>
                    <p>Bạn phải <a asp-action="GenerateRecoveryCodesWarning">Reset mã cứu hộ</a> đăng nhập trong trường hợp mất thiết bị Authenticator.</p>
                </div>
            }
            else if (Model.RecoveryCodesLeft == 1)
            {
                <div class="alert alert-danger">
                    <b>You have 1 recovery code left.</b>
                    <p>You can <a asp-action="GenerateRecoveryCodesWarning">generate a new set of recovery codes</a>.</p>
                </div>
            }
            else if (Model.RecoveryCodesLeft <= 3)
            {
                <div class="alert alert-warning">
                    <b>Bạn chỉ còn lại @Model.RecoveryCodesLeft mã cứu hộ.</b>
                    <p>Bạn nên <a asp-action="GenerateRecoveryCodesWarning">Reset mã cứu hộ</a> để phòng khi mất thiết bị Authenticator.</p>
                </div>
            }
            <a asp-action="GenerateRecoveryCodesWarning" class="btn btn-default">Reset mã cứu hộ</a>
        }
        <h5>Ứng dụng Authenticator</h5>
        @if (!Model.HasAuthenticator)
        {
            <a asp-action="EnableAuthenticator" class="btn btn-default">Thiết lập Authenticator</a>
        }
        else
        {
            <a asp-action="EnableAuthenticator" class="btn btn-default">Thiết lập Authenticator</a>
            <a asp-action="ResetAuthenticatorWarning" class="btn btn-default">Reset mã Authenticator</a>
        }
    </div>
    <h3>Địc chỉ IP: @Context.Request.HttpContext.Connection.RemoteIpAddress</h3>
</section>

TCV/TCVWeb/Areas/Admin/Views/HomeAdmin/ResetAuthenticator.cshtml
@{
    ViewBag.Title = "Reset mã Authenticator";
}
<section role="main" class="content-body">
    <header class="page-header">
        <h2><i class="fa @ViewBag.Icon"></i> @ViewBag.Title</h2>
        <div class="right-wrapper pull-right">
            <ol class="breadcrumbs">
                <li>
                    <a href="@Url.Action("Index", "Home")">
                        <i class="fa fa-home"></i>
                    </a>
                </li>
                <li><span>Authenticator</span></li>
            </ol>
            <a class="sidebar-right-toggle" data-open="sidebar-right"><i class="fa fa-chevron-left"></i></a>
        </div>
    </header>
    <div class="row">
        <div class="col-sm-4">
            <a class="btn btn-primary" href="@Url.Action("Index")"><i class="fa fa-undo"></i> Quay lại</a>
        </div>
        <div class="col-sm-8 text-right">
        </div>
    </div>
    <div class="mt-md">
        <div class="alert alert-warning" role="alert">
            <p>
                <span class="glyphicon glyphicon-warning-sign"></span>
                <b>Nếu bạn Reset mã Authenticator, bạn cần phải thực hiện lại thao tác thiết lập ứng dụng.</b>
            </p>
            <p>
                Thao tác này sẽ ngắt liên kết Authenticator cho đến khi bạn thực hiện lại các bước liên kết.
            </p>
        </div>
        <div>
            <form asp-action="ResetAuthenticator" method="post" class="form-group">
                <button class="btn btn-danger" type="submit">Reset mã Authenticator</button>
            </form>
        </div>
    </div>
</section>

TCV/TCVWeb/Areas/Admin/Views/HomeAdmin/ShowRecoveryCodes.cshtml
@using TCVWeb.Areas.Admin.Models
@model ShowRecoveryCodesViewModel
@{
    ViewBag.Title = "Danh sách mã cứu hộ";
}
<section role="main" class="content-body">
    <header class="page-header">
        <h2><i class="fa @ViewBag.Icon"></i> @ViewBag.Title</h2>
        <div class="right-wrapper pull-right">
            <ol class="breadcrumbs">
                <li>
                    <a href="@Url.Action("Index", "Home")">
                        <i class="fa fa-home"></i>
                    </a>
                </li>
                <li><span>Authenticator</span></li>
            </ol>
            <a class="sidebar-right-toggle" data-open="sidebar-right"><i class="fa fa-chevron-left"></i></a>
        </div>
    </header>
    <div class="row">
        <div class="col-sm-4">
            <a class="btn btn-primary" href="@Url.Action("Index")"><i class="fa fa-undo"></i> Quay lại</a>
        </div>
        <div class="col-sm-8 text-right">
        </div>
    </div>
    <div class="mt-md">
        <div class="alert alert-warning" role="alert">
            <p>
                <span class="glyphicon glyphicon-warning-sign"></span>
                <b>Cất giữ những mã cứu hộ này ở nơi an toàn.</b>
            </p>
            <p>
                Nếu bạn mất thiết bị, bạn có thể đăng nhập bằng mã cứu hộ.
            </p>
        </div>
        <div class="row">
            <div class="col-md-12">
                @for (var row = 0; row < Model.RecoveryCodes.Length; row += 2)
                {
                    <code>@Model.RecoveryCodes[row]</code><text>&nbsp;</text><code>@Model.RecoveryCodes[row + 1]</code><br />
                }
            </div>
        </div>
    </div>
</section>