TCV/TCVWeb/Areas/Admin/Controllers/BlogPostController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using TCVShared.Data;
using TCVShared.Helpers;
using TCVWeb.Areas.Admin.Models;

namespace TCVWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Manager,Operator")]
    public class BlogPostController : Controller
    {
        private readonly ILogger _logger;
        private readonly AppDBContext _dbContext;

        public BlogPostController(
            ILogger<BlogPostController> logger,
            AppDBContext dbContext)
        {
            _logger = logger;
            _dbContext = dbContext;
        }

        public IActionResult Index(PagedList<BlogPost> model)
        {
            var filterQuery = _dbContext.BlogPosts.Where(x => model.Search == null || x.Title.Contains(model.Search));
            var selectQuery = filterQuery.OrderByDescending(x => x.Id).Skip((model.CurPage - 1) * model.PageSize).Take(model.PageSize);

            model.TotalRows = filterQuery.Count();
            model.Content = selectQuery.ToList();

            return View(model);
        }

        public ActionResult Details(int id)
        {
            var model = _dbContext.BlogPosts.Find(id);
            if (model == null)
                return BadRequest();

            return View(model);
        }

        public ActionResult Create()
        {
            ViewBag.PostCats = _dbContext.PostCats.Select(x => new SelectItemModel() { id = x.Id, text = x.Name }).ToList();
            return View(new BlogPost());
        }

        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult Create(BlogPost model)
        {
            if (!ModelState.IsValid)
                return View(model);
            try
            {
                model.CreateUser = User.Identity.Name;
                model.UpdateUser = User.Identity.Name;
                model.CreateTime = DateTime.Now;
                if (model.Status == PostStatus.Normal || model.Status == PostStatus.Special)
                    model.PublishTime = DateTime.Now;
                if (model.Status == PostStatus.Pending || model.Status == PostStatus.Suspended)
                    model.PublishTime = null;
                _dbContext.BlogPosts.Add(model);

                if (model.PostCats != null)
                {
                    foreach (var catId in model.PostCats)
                    {
                        BlogPostTaxo newCat = new BlogPostTaxo()
                        {
                            TaxoId = catId,
                            PostId = model.Id,
                        };
                        _dbContext.BlogPostTaxoes.Add(newCat);
                    }
                }

                if (!string.IsNullOrEmpty(model.PostTags))
                {
                    string[] postTags = model.PostTags.Split(new char[] { ',' }, StringSplitOptions.RemoveEmptyEntries);
                    foreach (var tag in postTags)
                    {
                        string trTag = tag.Trim();
                        Taxonomy taxo = _dbContext.PostTags.FirstOrDefault(x => x.Name == trTag);
                        if (taxo == null)
                        {
                            taxo = new Taxonomy() { Type = TaxoType.PostTag, Name = trTag };
                            _dbContext.Taxonomies.Add(taxo);
                            _dbContext.SaveChanges();
                        }

                        BlogPostTaxo newTag = new BlogPostTaxo()
                        {
                            TaxoId = taxo.Id,
                            PostId = model.Id,
                        };
                        _dbContext.BlogPostTaxoes.Add(newTag);
                    }
                }
                _dbContext.SaveChanges();
                model = new BlogPost();
                return Redirect(Url.Action("Index"));
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View();
            }
        }

        public IActionResult Update(int id)
        {
            var model = _dbContext.BlogPosts.Find(id);
            if (model == null)
                return BadRequest();

            model.PostCats = (from x in _dbContext.Taxonomies
                              join y in _dbContext.BlogPostTaxoes on x.Id equals y.TaxoId
                              where y.PostId == id && x.Type == TaxoType.PostCat
                              select x.Id).ToArray();

            var postTags = (from x in _dbContext.Taxonomies
                            join y in _dbContext.BlogPostTaxoes on x.Id equals y.TaxoId
                            where y.PostId == id && x.Type == TaxoType.PostTag
                            select x.Name).ToArray();

            model.PostTags = string.Join(", ", postTags);

            model.LastStatus = model.Status;

            ViewBag.PostCats = _dbContext.PostCats.Select(x => new SelectItemModel() { id = x.Id, text = x.Name, selected = model.PostCats.Contains(x.Id) }).ToList();
            return View(model);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult Update(BlogPost model)
        {
            if (ModelState.IsValid)
            {
                model.LastUpdate = DateTime.Now;
                model.UpdateUser = User.Identity.Name;
                if (model.Status == PostStatus.Normal || model.Status == PostStatus.Special)
                    model.PublishTime = DateTime.Now;
                if (model.Status == PostStatus.Pending || model.Status == PostStatus.Suspended)
                    model.PublishTime = null;

                _dbContext.Entry(model).State = EntityState.Modified;
                _dbContext.SaveChanges();

                // Remove all taxoes
                var delItems = (from item in _dbContext.BlogPostTaxoes
                                where item.PostId == model.Id
                                select item);

                foreach (var item in delItems)
                    _dbContext.BlogPostTaxoes.Remove(item);

                // Add cats
                if (model.PostCats != null)
                {
                    foreach (var catId in model.PostCats)
                    {
                        BlogPostTaxo newCat = new BlogPostTaxo()
                        {
                            TaxoId = catId,
                            PostId = model.Id,
                        };
                        _dbContext.BlogPostTaxoes.Add(newCat);
                    }
                }

                // Add tags
                if (!string.IsNullOrEmpty(model.PostTags))
                {
                    string[] postTags = model.PostTags.Split(new char[] { ',' }, StringSplitOptions.RemoveEmptyEntries);
                    foreach (var tag in postTags)
                    {
                        string trTag = tag.Trim();
                        Taxonomy taxo = _dbContext.PostTags.FirstOrDefault(x => x.Name == trTag);
                        if (taxo == null)
                        {
                            taxo = new Taxonomy() { Type = TaxoType.PostTag, Name = trTag };
                            _dbContext.Taxonomies.Add(taxo);
                            _dbContext.SaveChanges();
                        }

                        BlogPostTaxo newTag = new BlogPostTaxo()
                        {
                            TaxoId = taxo.Id,
                            PostId = model.Id,
                        };

                        _dbContext.BlogPostTaxoes.Add(newTag);
                    }
                }

                _dbContext.SaveChanges();
                return RedirectToAction("Details", new { @id = model.Id });
            }

            ViewBag.PostCats = _dbContext.PostCats.Select(x => new SelectItemModel() { id = x.Id, text = x.Name, selected = model.PostCats.Contains(x.Id) }).ToList();
            return View(model);
        }

        // GET: BlogPost/Delete/5
        public IActionResult Delete(int? id)
        {
            var model = _dbContext.BlogPosts.Find(id);
            if (model == null)
                return NotFound();

            return View(model);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult Delete(BlogPost model)
        {
            try
            {
                _dbContext.Entry(model).State = EntityState.Deleted;
                _dbContext.SaveChanges();
                return Json(new ModalFormResult() { Code = 1 });
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
            }

            return View(model);
        }

        public ActionResult PostCatList(PagedList<Taxonomy> model)
        {
            var filterQuery = _dbContext.PostCats.Where(x => model.Search == null || x.Name.Contains(model.Search));
            var selectQuery = filterQuery.OrderByDescending(x => x.Id).Skip((model.CurPage - 1) * model.PageSize).Take(model.PageSize);

            model.TotalRows = filterQuery.Count();
            model.Content = selectQuery.ToList();

            return View(model);
        }

        public ActionResult PostCatCreate()
        {
            ViewBag.ParentId = new SelectList(_dbContext.PostCats, "Id", "Name");
            return View("PostCatEdit", new Taxonomy());
        }

        [HttpPost, ValidateAntiForgeryToken]

TCV/TCVWeb/Controllers/BlogPostController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TCVShared.Data;
using TCVShared.Helpers;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using TCVWeb.Models;
using TCVWeb.Areas.Admin.Models;

namespace TCVWeb.Controllers
{
    public class BlogPostController : Controller
    {
        private readonly AppDBContext _dbContext;
        private readonly ILogger<BlogPostController> _logger;
        private readonly UserManager<AppUser> _userManager;

        public BlogPostController(AppDBContext dbContext,
            ILogger<BlogPostController> logger,
            UserManager<AppUser> userManager)
        {
            _dbContext = dbContext;
            _logger = logger;
            _userManager = userManager;
        }
        // GET: BlogPost
        public async Task<IActionResult> Index(PagedList<BlogPost> model, int pageSize)
        {
            var filterQuery = _dbContext.BlogPosts.Where(x => model.Search == null || x.Title.Contains(model.Search));
            var selectQuery = filterQuery.OrderByDescending(x => x.Id).Skip((model.CurPage - 1) * model.PageSize).Take(model.PageSize);

            model.TotalRows = filterQuery.Count();
            model.Content = await selectQuery.ToListAsync();
            model.PageSize = pageSize != 0 ? pageSize : 12;

            return View(model);
        }

         //GET: BlogPost/Details/5
        public ActionResult Details(int id)
        {
            ViewBag.PostCats = _dbContext.PostCats.Select(x => new SelectItemModel() { id = x.Id, text = x.Name }).ToList();
            var blogModel = _dbContext.BlogPosts.FirstOrDefault(blog => blog.Id == id);
            return View(blogModel);
        }

        private List<Taxonomy> GetTagsItem(int? id)
        {
            var idTaxos = _dbContext.BlogPostTaxoes.Where(x => x.PostId == id).Select(x => x.TaxoId).ToList();
            List<Taxonomy> taxoTags = _dbContext.Taxonomies.Where(x => idTaxos.Contains(x.Id) && x.Type == TaxoType.PostTag).ToList();
            foreach (var item in idTaxos)
            {
                var taxo = _dbContext.Taxonomies.FirstOrDefault(x => x.Id == item && x.Type == TaxoType.PostTag);
                if (taxo != null && taxo.ParentId != null)
                    if (!idTaxos.Contains(taxo.Id))
                        taxoTags.Add(taxo);
                    else
                    {
                        if (!idTaxos.Contains(taxo.Id))
                            taxoTags.Add(taxo);
                        var parent = _dbContext.Taxonomies.Find(taxo.ParentId);
                        if (!idTaxos.Contains(parent.Id))
                            taxoTags.Add(parent);
                    }
            }
            return taxoTags;
        }

        //// GET: BlogPost/Create
        //[HttpPost]
        //public ActionResult Create(BlogPost model)
        //{
        //    if (!ModelState.IsValid)
        //        return View(model);
        //    try
        //    {
        //        model.CreateUser = User.Identity.Name;
        //        model.UpdateUser = User.Identity.Name;
        //        model.CreateTime = DateTime.Now;
        //        if (model.Status == PostStatus.Normal || model.Status == PostStatus.Special)
        //            model.PublishTime = DateTime.Now;
        //        _dbContext.BlogPosts.Add(model);

        //        if (model.PostCats != null)
        //        {
        //            foreach (var catId in model.PostCats)
        //            {
        //                BlogPostTaxo newCat = new BlogPostTaxo()
        //                {
        //                    TaxoId = catId,
        //                    PostId = model.Id,
        //                };
        //                _dbContext.BlogPostTaxoes.Add(newCat);
        //            }
        //        }

        //        if (!string.IsNullOrEmpty(model.PostTags))
        //        {
        //            string[] postTags = model.PostTags.Split(new char[] { ',' }, StringSplitOptions.RemoveEmptyEntries);
        //            foreach (var tag in postTags)
        //            {
        //                string trTag = tag.Trim();
        //                Taxonomy taxo = _dbContext.PostTags.FirstOrDefault(x => x.Name == trTag);
        //                if (taxo == null)
        //                {
        //                    taxo = new Taxonomy() { Type = TaxoType.PostTag, Name = trTag };
        //                    _dbContext.Taxonomies.Add(taxo);
        //                    _dbContext.SaveChanges();
        //                }

        //                BlogPostTaxo newTag = new BlogPostTaxo()
        //                {
        //                    TaxoId = taxo.Id,
        //                    PostId = model.Id,
        //                };
        //                _dbContext.BlogPostTaxoes.Add(newTag);
        //            }
        //        }
        //        _dbContext.SaveChanges();
        //        model = new BlogPost();
        //        return View(model);
        //    }
        //    catch (Exception ex)
        //    {
        //        ModelState.AddModelError("", ex.Message);
        //        return View();
        //    }
        //}


        //private List<Taxonomy> GetCategoriesItem(int? id)
        //{
        //    var idTaxos = _dbContext.BlogPostTaxoes.Where(x => x.PostId == id).Select(x => x.TaxoId).ToList();
        //    List<Taxonomy> taxoCates = _dbContext.Taxonomies.Where(x => idTaxos.Contains(x.Id) && x.Type == TaxoType.PostCat).ToList();
        //    foreach (var item in idTaxos)
        //    {
        //        var taxo = _dbContext.Taxonomies.FirstOrDefault(x => x.Id == item && x.Type == TaxoType.PostCat);
        //        if (taxo != null && taxo.ParentId != null)
        //            if (!idTaxos.Contains(taxo.Id))
        //                taxoCates.Add(taxo);
        //            else
        //            {
        //                if (!idTaxos.Contains(taxo.Id))
        //                    taxoCates.Add(taxo);
        //                var parent = _dbContext.Taxonomies.Find(taxo.ParentId);
        //                if (!idTaxos.Contains(parent.Id))
        //                    taxoCates.Add(parent);
        //            }
        //    }
        //    return taxoCates;
        //}

    }
}

TCV/TCVWeb/Views/BlogPost/Category.cshtml

@{
    ViewData["Title"] = "Category";
}

<h2>Category</h2>


TCV/TCVWeb/Views/BlogPost/Details.cshtml
@addTagHelper *,TCV.Shared
@model BlogPost
@{
    ViewData["Title"] = "Details";
}

<div role="main" class="main">
    <section class="page-header">
        <div class="container">
            <ul class="breadcrumb">
                <li><a href="#">Trang chủ</a></li>

                <li><a href="#">Blog</a></li>
                <li class="active"> @Html.DisplayFor(m => Model.Title) </li>
            </ul>
        </div>
    </section>

    <div class="container">
        <div class="row">
            <div class="col-md-9">
                <div class="blog-posts single-post">

                    <article class="post post-large blog-single-post">
                        @if (Model.Format == PostFormat.Gallery)
                        {
                            <div class="post-image">
                                <div class="owl-carousel owl-theme" data-plugin-options="{'items':1}">
                                    <div>
                                        <div class="img-thumbnail">
                                            <img class="img-responsive" src="~/img/demos/shop/blog/blog-shop-4.jpg" alt="Post">
                                        </div>
                                    </div>
                                    <div>
                                        <div class="img-thumbnail">
                                            <img class="img-responsive" src="@Html.DisplayFor(m => Model.Image)" alt="Post">
                                        </div>
                                    </div>

                                </div>
                            </div>
                        }
                        else if (Model.Format == PostFormat.Video)
                        {
                            <div class="post-video">
                                @Html.Raw(Model.ExtLink)
                            </div>
                        }

                        <div class="post-date">
                            <span class="day">@Model.CreateTime.Value.Day.ToString()</span>
                            <span class="month">Tháng @Model.CreateTime.Value.Month.ToString()</span>
                        </div>

                        <div class="post-content">

                            <h2><a href="#">@Model.Title</a></h2>

                            <div class="post-meta">
                                <span><i class="fa fa-user"></i> By <a href="#">@Model.CreateUser</a> </span>
                                <span><i class="fa fa-tag"></i> <a href="#">News</a> </span>
                                @*<span><i class="fa fa-comments"></i> <a href="#">12 Comments</a></span>*@
                            </div>

                            @Html.Raw(Model.Content)


                            <div class="post-block post-share">
                                <h3 class="h4 heading-primary"><i class="fa fa-share"></i>Share this post</h3>

                                <!-- AddThis Button BEGIN -->
                                <div class="addthis_toolbox addthis_default_style ">
                                    <a class="addthis_button_pinterest_pinit"></a>
                                    <a class="addthis_counter addthis_pill_style"></a>
                                    <div class="fb-like" data-href="https://localhost:5001/BlogPost/Details/@Model.Id" data-layout="standard" data-action="like" data-size="small" data-show-faces="true" data-share="false"></div>
                                </div>

                                <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=xa-50faf75173aadc53"></script>
                                <!-- AddThis Button END -->
                            </div>
                            <div class="fb-comments" data-href="http://www.ticivi.com/BlogPost/Details/@Model.Id" data-width="100%" data-numposts="5"></div>

                        </div>
                    </article>

                </div>
            </div>

            @*<partial name="_PartialRightBlog" />*@

        </div>
    </div>

</div>


TCV/TCVWeb/Views/BlogPost/Index.cshtml
@addTagHelper *,TCVShared
@model PagedList<BlogPost>
@{
    ViewBag.Icon = "fas fa-archive";
    ViewBag.Title = "Bài Viết";
}

<div role="main" class="main">
    <section class="page-header">
        <div class="container">
            <ul class="breadcrumb">
                <li><a href="#">Trang chủ</a></li>

                <li class="active">Bài viết</li>
            </ul>
        </div>
    </section>

    <div class="container">
        <div class="row">
            <div class="col-md-9">
                <div class="toolbar">
                    <div class="sorter">
                        <div class="sort-by">
                            <label>Sắp theo:</label>
                            <select>
                                <option value="Created At">Ngày tạo</option>
                                <option value="Added By">Tác giả</option>
                            </select>
                            <a href="#" title="Set Desc Direction">
                                <img src="../img/demos/shop/i_desc_arrow.gif" alt="Set Desc Direction">
                            </a>
                        </div>
                    </div>
                </div>

                <div class="blog-posts">
                    @foreach (var item in Model.Content)
                    {
                        <article class="post post-large">
                            @if (item.Format == PostFormat.Gallery)
                            {
                                @*foreach (var mediaFile in item.MediaAlbum.MediaFiles)
                                {*@
                                    <div class="post-image">
                                        <div class="owl-carousel owl-theme" data-plugin-options="{'items':1}">
                                            <div>
                                                <div class="img-thumbnail">
                                                    <img class="img-responsive" src="@item.Image" alt="Post" style="width:1280px; height: 400px; object-fit:fill; object-position:center">
                                                </div>
                                            </div>

                                        </div>
                                    </div>

                                @*}*@
                            }
                            else if (item.Format == PostFormat.Video)
                            {
                                    <div class="post-video">
                                        @Html.Raw(item.ExtLink)
                                    </div>
                            }

                            <div class="post-date">
                                <span class="day">@item.CreateTime.Value.Day.ToString()</span>
                                <span class="month">Tháng @item.CreateTime.Value.Month.ToString()</span>
                            </div>

                            <div class="post-content">
                                <h2><a href="@Url.Action("Details","BlogPost",new { id = item.Id })">@Html.DisplayFor(m => item.Title)</a></h2>
                                <p>@Html.DisplayFor(m => item.Preview)</p>

                                <a href="@Url.Action("Details","BlogPost",new { id = item.Id })" class="btn btn-xs btn-link">Đọc tiếp</a>

                                <div class="post-meta">
                                    <span><i class="fa fa-calendar"></i>@Html.DisplayFor(m => item.CreateTime) </span>
                                    <span><i class="fa fa-user"></i> By <a href="#">@Html.DisplayFor(m => item.CreateUser)</a> </span>
                                    <span><i class="fa fa-tag"></i> <a href="#">News</a> </span>
                                </div>
                            </div>
                        </article>
                    }
                </div>

                <div class="toolbar">
                    <div class="sorter">
                        <div class="sort-by">
                            <label>Sắp theo:</label>
                            <select>
                                <option value="Created At">Ngày tạo</option>
                                <option value="Added By">Tác giả</option>
                            </select>
                            <a href="#" title="Set Desc Direction">
                                <img src="../img/demos/shop/i_desc_arrow.gif" alt="Set Desc Direction">
                            </a>
                        </div>

                        <ul class="pagination">
                            <pagination model="@Model" query-string="@Context.Request.QueryString" css-style="pagination pagination-sm"></pagination>
                        </ul>
                       
                    </div>
                </div>
            </div>

            <partial name="_PartialRightBlog" />

        </div>
    </div>

</div>
